/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "simple.v:1.1-13.10" *)
module C1(A0, A1, SA, B0, B1, SB, S0, S1, F);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "simple.v:2.11-2.13" *)
  input A0;
  wire A0;
  (* src = "simple.v:2.15-2.17" *)
  input A1;
  wire A1;
  (* src = "simple.v:3.11-3.13" *)
  input B0;
  wire B0;
  (* src = "simple.v:3.15-3.17" *)
  input B1;
  wire B1;
  (* src = "simple.v:5.12-5.13" *)
  output F;
  wire F;
  (* src = "simple.v:4.11-4.13" *)
  input S0;
  wire S0;
  (* src = "simple.v:4.15-4.17" *)
  input S1;
  wire S1;
  (* src = "simple.v:2.19-2.21" *)
  input SA;
  wire SA;
  (* src = "simple.v:3.19-3.21" *)
  input SB;
  wire SB;
  NOR _3_ (
    .A(S0),
    .B(S1),
    .Y(_0_)
  );
  MUX _4_ (
    .A(B1),
    .B(B0),
    .S(SB),
    .Y(_1_)
  );
  MUX _5_ (
    .A(A1),
    .B(A0),
    .S(SA),
    .Y(_2_)
  );
  MUX _6_ (
    .A(_2_),
    .B(_1_),
    .S(_0_),
    .Y(F)
  );
endmodule
